apiVersion: v1
kind: Service
metadata:
  name: go-web
  labels:
    app: go-web
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    run: go-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: go-web
        app: go-web
    spec:
      containers:
      - name: go-web
        image: chzbrgr71/go-guestbook:4
        env:
        - name: SQLSERVER
          value: "guestbook-db.default.svc.cluster.local"
        - name: SQLPORT
          value: "10433"
        - name: SQLID
          value: "sa"
        - name: SQLPWD
          value: "Pass@word"
        - name: SQLDB
          value: "sql_guestbook"
        ports:
          - containerPort: 8080