apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guestbook-web
spec:
  replicas: 4
  template:
    metadata:
      labels:
        run: guestbook-web
        app: guestbook-web
    spec:
      containers:
      - name: guestbook-web
        image: chzbrgr71/guestbook-web
        env:
        - name: SQLSERVER
          value: "10.0.31.81"
        - name: SQL_ID
          value: "sa"
        - name: SQL_PWD
          value: "Pass@word"
        - name: ASPNETCORE_URLS
          value: "http://+:5000"
        ports:
          - containerPort: 5000